# 운영 환경, 보안, 안정성, 성능에 초점

spring:
  config:
    activate:
      on-profile: prod

  datasource: # 보안 목적으로 ${변수명} 사용
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate  # 검증
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

file:
  upload-dir: ${FILE_UPLOAD_DIR:/app/uploads}

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.springframework.web: info
