# 로컬 환경에만 적용
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    # 인메모리 (권장) -> 휘발성 db, 서버 실행 동안만 존재하는 임시 db. 가볍고 빠름.
    url: jdbc:h2:mem:blogdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    # 임베디드 (data가 넣어지지 않음)
#    url: jdbc:h2:file:./data/blogdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;AUTO_SERVER=TRUE
    # 서버모드 -> h2 DB 실행 필요
#    url: jdbc:h2:tcp://localhost:9092/~/blogdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

# h2 = 가볍고 빠른 RDB. 주로 테스트용으로 많이 사용
  h2:
    console:
      enabled: true # 웹 콘솔 활성화
      path: /h2-console # 접속 URL: http://localhost:8080/h2-console
      # jdbc:h2:mem:blogdb
      # jdbc:h2:file:./data/blogdb

logging:
  level:
    # Hibernate SQL
    # Hibernate : Java에서 DB를 쉽게 다루기 위해 만들어진 ORM 프레임워크. SQL 쿼리 자동 생성
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace

    # Spring Web
    org.springframework.web: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

    # 사용자 package
    com.codeit.blog: trace
